language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t manikkhosla/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manikkhosla/docker-react  npm run test

